FROM node:16-alpine
# EACCES: permission denied で追加
USER node

RUN mkdir -p /home/node/app
# WORKDIR '/app'
WORKDIR /home/node/app
# COPY ./package.json ./
COPY --chown=node:node ./package.json ./
RUN npm install
# COPY . .
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]